# Prometheus configuration for monitoring FastAPI application

global:
  scrape_interval: 15s      # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate rules

# Rule files (for alerting)
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor FastAPI application
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['api:8000']  # FastAPI service name and port
    metrics_path: '/metrics'   # Endpoint where FastAPI exposes metrics
    scrape_interval: 10s       # Scrape every 10 seconds
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Monitor PostgreSQL (requires postgres_exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']  # If you add postgres_exporter
    scrape_interval: 30s

  # Monitor Docker containers (requires cAdvisor)
  - job_name: 'docker-containers'
    static_configs:
      - targets: ['cadvisor:8080']  # If you add cAdvisor
    scrape_interval: 30s

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093